project:
  customer: k8s lab 
  project: Learn k8s fce
  opportunity: fce training 
  sku: k8s
  arch: kubernetes
  hw: approved
layers:
- name: baremetal
  type: baremetal
  config:
    hosts: include-rel://config/hosts.yaml
- name: maas
  type: maas
  parent: baremetal
  config:
    tweaks:
    - nobond
    - nobridge
    - nomaasha
    - nopgha
    - nojujuha
    maas_vip: 172.16.224.2
    package_repositories: [] # optional dict
      # For params see: 'maas playground package-repositories create --help'
    maas_config: # optional dict
      # For params see: 'maas profile maas set-config --help'
       dnssec_validation: 'no'
       upstream_dns: 8.8.8.8
       # If a proxy is required, set this
       # http_proxy: FCE_TEMPLATE
    maas_boot_source_selections:
    - release: 'bionic'
      arches: ['amd64']
    maas_admin: telescreen
    maas_admin_email: ha@buihanotes.com
    maas_admin_password: password
    infra_extra_repositories:
    - ppa:maas/2.7
    networks: include-rel://config/networks.yaml
    enlist_timeout: 1801
    nodeconfig: include-rel://config/bucketsconfig.yaml
    nodes: include-rel://config/nodes.yaml
- name: juju_maas_controller
  type: juju_maas_controller
  parent: maas
  config:
    #ha: 3
    #ha_timeout: 900
    controller_name: foundations-maas
    model_defaults: # optional dict
      # see: 'juju model-config --help'
      # If a proxy is required, set it here
      # juju-http-proxy: FCE_TEMPLATE
      # juju-https-proxy: FCE_TEMPLATE
      # apt-http-proxy: FCE_TEMPLATE
      # apt-https-proxy: FCE_TEMPLATE
      # snap-http-proxy: FCE_TEMPLATE
      # snap-https-proxy: FCE_TEMPLATE
      juju-no-proxy: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
      automatically-retry-hooks: false
- name: kubernetes
  type: kubernetes
  parent: juju_maas_controller
  config:
    juju_model: kubernetes
    wait_exclude: ['hacluster-kubernetes-master'] # XXX: bug 1841005
    bundles: # Primary bundle followed by optional overlays.
    - kubernetes_bundle.yaml
    crashdump:
      addons:
        - config
        - k8s-pod-logs
    # validate:
    #   OPTIONAL: Runs through our k8s team's validation suite:
    #   https://github.com/charmed-kubernetes/jenkins/blob/master/jobs/integration/validation.py
    # - type: integration
