- name: Install necessary packages for docker CE
  become: true
  ansible.builtin.apt:
    pkg:
      - chrony
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest
    update_cache: true

- name: Remove "docker." package
  become: true
  ansible.builtin.apt:
    name: docker.io
    state: absent

- name: Add Docker gpg key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: run apt update
  become: yes
  apt:
    update_cache: yes

- name: Install Docker
  become: yes
  apt:
    name: docker-ce
  notify:
    - add_user_to_docker_group
    - restart_docker_daemon
  changed_when: yes

- meta: flush_handlers