allocations:
  hyperconverged:
    machines:
      - hc0.maas
      - hc1.maas
      - hc2.maas
      - hc3.maas
      - hc4.maas
 
  jujuctl:
    machines:
      - ctl.maas

configs:
  jujuctl:
    nics:
    - id: ens0
      nic: 0
      name: ens0
      type: physical
      mtu: 1500
      fabric: fabric-0
      vlan_id: 0
      subnets: ['oam']
    disks:
    - id: vda
      type: disk
      disk: 0
      ptable: MBR
    - id: vda-part1
      type: partition
      device: vda
      number: 1
      size: 16G
    - id: vda-part1-format
      type: format
      fstype: ext4
      label: root
      volume: vda-part1
    - id: vda-part1-mount
      type: mount
      device: vda-part1-format
      path: /

  hyperconverged:
    nics:
    - id: ens0
      nic: 0
      name: ens0
      type: physical
      mtu: 1500
      fabric: fabric-0
      vlan_id: 0
      subnets: ['oam']
    - id: ens1
      nic: 1
      name: ens1
      type: physical
      mtu: 1500
      fabric: fabric-0
      vlan_id: 225
      subnets: ['external']
    - id: ens2
      nic: 2
      name: ens2
      type: physical
      mtu: 1500
      fabric: fabric-0
      vlan_id: 226
      subnets: ['internal']

    disks:
    # Add 4 disk. 
    # Disk layout is as below. Adjusting accordingly
    # disk0: root
    # disk1: osd
    # disk2: caching device
    - id: disk0
      type: disk
      disk: 0
    - id: disk1
      disk: 1
      type: disk
      ptable: gpt
    - id: disk2
      disk: 2
      type: disk
      ptable: gpt
    # Partition disk0 as bcache caching device
    # Parition 1 of disk 0 is caching device for disk1 (boot)
    # Partition 2 of disk 0 is caching device for disk2 (osd)
    - id: disk2-part1
      device: disk2
      number: 1
      size: 6G
      type: partition
    - id: disk2-part2
      device: disk2
      number: 2
      size: 10G
      type: partition
    # Format disk 0. 2 Partitions: boot and root
    - id: disk0-part1
      device: disk0
      type: partition
      number: 1
      size: 500M
    - id: disk0-part2
      device: disk0
      type: partition
      number: 2
      size: 9.5G
    # Bcache
    - id: disk0-part1-format
      device: disk0-part1
      volume: disk0-part1
      type: format
      fstype: ext4
      label: boot
    - id: disk0-part1-mount
      device: disk0-part1-format
      type: mount
      path: /boot
    - backing_device: disk0-part2
      cache_device: disk2-part1
      cache_mode: writeback
      id: bcache0
      name: bcache0
      type: bcache
    - id: bcache0-format
      label: os
      type: format
      volume: bcache0
      fstype: ext4
    - id: disk0-part2-mount
      device: bcache0-format
      path: /
      type: mount
    # OSD Devices
    - backing_device: disk1
      cache_device: disk2-part2
      cache_mode: writeback
      id: bcache1
      name: bcache-osd-1
      type: bcache
    
