description: A mini k8s cluster for testing

variables:
  kubernetes-channel: &kubernetes-channel 1.16/stable

machines:
  '0':
    constraints: cores=1 mem=2G root-disk=16G
    series: bionic
    tags: hc
  '1':
    constraints: cores=1 mem=2G root-disk=16G
    series: bionic
    tags: hc
  '2':
    constraints: cores=1 mem=2G root-disk=16G
    series: bionic
    tags: hc
  '3':
    constraints: cores=1 mem=2G root-disk=16G
    series: bionic
    tags: hc
  
services:
  containerd:
    charm: cs:~containers/containerd
  easyrsa:
    charm: cs:~containers/easyrsa
    num_units: 1
    to:
    - 0
  etcd:
    charm: cs:~containers/etcd
    num_units: 1
    options:
      channel: 3.2/stable
    to:
    - 0
  kubernetes-master:
    charm: cs:~containers/kubernetes-master
    num_units: 1
    options:
      allow-privileged: "true"
      channel: *kubernetes-channel
      authorization-mode: RBAC
    resources:
      cdk-addons: 0
    to:
    - 0
  kubernetes-worker:
    charm: cs:~containers/kubernetes-worker
    expose: true
    num_units: 3
    options:
      ingress: true
      channel: *kubernetes-channel
    to:
    - 1
    - 2
    - 3

relations:
- - kubernetes-master:kube-api-endpoint
  - kubernetes-worker:kube-api-endpoint
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - containerd
  - kubernetes-worker:container-runtime
- - containerd
  - kubernetes-master:container-runtime

