#cloud-config
no-log-init: true
users:
  - name: ubuntu
    gecos: Ubuntu User
    primary_group: ubuntu
    groups: users
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$0SSkAaAjMmpvEAmH$J.a1O3IhQ5EejvtALUdt9DUEtZ6K9eTq4ICClDAu6ngAeMMrmDK/hSfW3URZ92LjdD4MTnJ/yJmSn1oRwEZox/"
    ssh_import_id:
      - gh:telescreen

snap:
  commands:
    0: snap install lxd --channel=5.21/stable --cohort="+"
    1: snap install microceph --channel=squid/stable --cohort="+"
    2: snap install microovn --channel=24.03/stable --cohort="+"
    4: snap install microcloud --channel=2/stable --cohort="+"
