#cloud-config
no-log-init: true
preserve_hostname: false
fqdn: sts.test
hostname: adclient
users:
  - name: ubuntu
    gecos: Ubuntu User
    primary_group: ubuntu
    groups: users
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$0SSkAaAjMmpvEAmH$J.a1O3IhQ5EejvtALUdt9DUEtZ6K9eTq4ICClDAu6ngAeMMrmDK/hSfW3URZ92LjdD4MTnJ/yJmSn1oRwEZox/"
    ssh_import_id:
      - gh:telescreen
network:
  version: 2
  ethernets: 
    ens3:
      dhcp4-overrides:
        use-dns: false
        use-domains: false
      nameservers:
        search: [sts.test]

packages:
  - sssd-ldap

write_files:
  - owner: root:root
    path: /etc/sssd/sssd.conf
    permissions: 0600
    content: |
      [sssd]
      config_file_version = 2
      domains = example.com

      [domain/example.com]
      id_provider = ldap
      auth_provider = ldap
      chpass_provider = ldap
      ldap_uri = ldap://slapd00
      ldap_search_base = dc=example,dc=com
